#! /bin/bash

schema=("User" "Item" "Bid" "ItemCategory")

for i in "${schema[@]}"
do
	rm "$i.dat" 2>/dev/null
	touch "$i.dat"
done

ROOT_PATH='debug'

for file in "$ROOT_PATH/*.xml"
do
	for relation in "${schema[@]}"
	do
		python parser.py $file -class $relation >> "$relation.dat"
	done	
done

for relation in "${schema[@]}"
do
	orig="$relation.dat"
	temp="$relation.dat.temp"

	cat "$orig" | sort | uniq > "$temp"
	cat "$temp" > "$orig"
	rm "$temp"
done

